### PR TITLE
Issue 92  exceptions

### PR DESCRIPTION
**Pull request by adler-j**
This is quite well progressed now. My big note is that it seems we barely have any tests for the domain/range tests in `Operator` and no tests for the domain of `LinearSpace.norm` etc, we should add this (perhaps a separate pull)?

### CODE REVIEW

**Comment by adler-j** [comment]
It seems coveralls is angry with me, perhaps I should add tests for the exceptions.

**Comment by kohr-h** [comment]
Jenkins build on Python 2.7 fails:
```
File "/data/jenkins/workspace/odl-py2.7-issue-all/conftest.py", line 24, in <module>
    from odl import CUDA_AVAILABLE
  File "/data/jenkins/workspace/odl-py2.7-issue-all/odl/__init__.py", line 54, in <module>
    from . import trafos
  File "/data/jenkins/workspace/odl-py2.7-issue-all/odl/trafos/__init__.py", line 30, in <module>
    from . import wavelet
  File "/data/jenkins/workspace/odl-py2.7-issue-all/odl/trafos/wavelet/__init__.py", line 22, in <module>
ImportError: cannot import name wavelet
```
This used to be the error before when `PyWavelets` were not installed, but that's fixed now, so there must be something fishy in that module.

Python 3.4 succeeds.

**Comment by adler-j** [comment]
`odl/trafos/wavelet/__init__.py` does not exist on master. I suggest you clean the repo between each pull.

**Comment by kohr-h** [comment]
You're right. With the "wipe repository and force clone" it works now.

**Comment by kohr-h** [comment]
I think this looks good. Merge.
